### ISSUE TITLE
XHR issue

### ISSUE THREAD

**Issue by msimonc** [ruanyf/react-babel-webpack-boilerplate#10]
Hi, thanks for this, I get this in console log:

GET http://0.0.0.0:8080/socket.io/?EIO=3&transport=polling&t=1450823884019-16 Request.create @ polling-xhr.js:232Request @ polling-xhr.js:155XHR.request @ polling-xhr.js:86XHR.doPoll @ polling-xhr.js:116Polling.poll @ polling.js:118Polling.doOpen @ polling.js:62Transport.open @ transport.js:82Socket.open @ socket.js:220Socket @ socket.js:102Socket @ socket.js:37Manager.open.Manager.connect @ manager.js:205(anonymous function) @ manager.js:470
localhost/:1 

XMLHttpRequest cannot load http://0.0.0.0:8080/socket.io/?EIO=3&transport=polling&t=1450823884019-16. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8080' is therefore not allowed access. The response had HTTP status code 404.

**Comment by ruanyf** [comment]
Is the link helpful? https://github.com/webpack/webpack-dev-server/issues/69#issuecomment-60086566
