### ISSUE TITLE
IE 8 兼容

### ISSUE THREAD

**Issue by zhaotoday** [ruanyf/react-babel-webpack-boilerplate#13]
这个 demo 运行后在 IE8 下报错，加上 es5-shim 也不行。
怎么兼容 IE 8。

**Comment by ruanyf** [comment]
好像不行呢。

**Comment by zhaotoday** [comment]
下午弄了下，用 babel-polyfill 可以。
webpack.config.js 中的 devServer.inline 需设为 false。
可以根据浏览器版本判断是否用 script 标签引入 babel-polyfill。

**Comment by ruanyf** [comment]
还是不建议在IE8使用，React 与 Webpack 的行为难以预料。

**Comment by zhaotoday** [comment]
就是说如果要兼容 IE 8，建议不用 react+webpack？

**Comment by ruanyf** [comment]
是的。使用 jQuery + ES5

**Comment by zhaotoday** [comment]
好的，谢谢。
