### ISSUE TITLE
git clone 地址需要改下

### ISSUE THREAD

**Issue by yinzSE** [ruanyf/react-babel-webpack-boilerplate#14]
>First, you should clone the repo and install the dependencies.
```
$ git clone git@github.com:ruanyf/react-babel-webpack-boilerplate.git <yourAppName>
$ cd <yourAppName>
$ npm install
```

`$ git clone https://github.com/ruanyf/react-babel-webpack-boilerplate.git <yourAppName>`

**Comment by ruanyf** [comment]
If you use Windows, the protocol should be `https` other than `git`.

**Comment by yinzSE** [comment]
>The authenticity of host 'github.com (192.30.252.131)' can't be established.
RSA key fingerprint is SHA256:***.
Are you sure you want to continue connecting (yes/no)?
