### ISSUE TITLE
可否对里面的某些模块的使用作下简要说明

### ISSUE THREAD

**Issue by minooo** [ruanyf/react-babel-webpack-boilerplate#17]
知其然，也要知其所以然，
诸如：commitizen之类的模块为什么要用？用了有什么好处？可否作下简要说明呢。

**Comment by ruanyf** [comment]
好的，下次更新的时候会加上说明。

至于commitizen模块，可以参考这里
http://www.ruanyifeng.com/blog/2016/01/commit_message_change_log.html
