### ISSUE TITLE
多页面入口文件如何配置

### ISSUE THREAD

**Issue by tugenhua0707** [ruanyf/react-babel-webpack-boilerplate#21]
阮一峰，我想问下，如果我有这样的构建项目需求，我项目中可能有多个页面，有多个入口js和css文件，我想通过热加载去监听，如何配置

**Comment by ruanyf** [comment]
看这个例子。

https://github.com/ruanyf/webpack-demos#demo02-multiple-entry-files-source

**Comment by tugenhua0707** [comment]
恩 我想说的不是这个意思~
