### ISSUE TITLE
npm run lint同样报错

### ISSUE THREAD

**Issue by yuanzm** [ruanyf/react-babel-webpack-boilerplate#22]
报错内容：
‘jsx)'’不是内部或外部命令，也不是可运行的程序或批处理文件。
运行环境：
- Windows 10
- npm v3.10.3
- node v6.3.0

**Comment by ruanyf** [comment]
请提供完整的报错提示。

**Comment by ruanyf** [comment]
Windows 命令行下，该命令不可用。
