### ISSUE TITLE
node6/npm3报错

### ISSUE THREAD

**Issue by yangshipo** [ruanyf/react-babel-webpack-boilerplate#25]
环境：
node v6.9.1
npm  v3.10.9
os win7p 64位
现象：
npm start 报错

-----------------------------------------------------------------------------------------
·
 70% 1/1 build modulesevents.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 127.0.0.1:8080
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at Server._listen2 (net.js:1244:19)
    at listen (net.js:1293:10)
    at net.js:1403:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:62:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:81:10)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "C:\\Users\\admin\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.9
npm ERR! code ELIFECYCLE
npm ERR! react-babel-webpack-boilerplate@1.2.2 start: `webpack-dev-server --devtool eval --progress --hot --content-base app`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-babel-webpack-boilerplate@1.2.2 start script 'webpack-dev-server --devtool eval --progress --hot --content-base app'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the react-babel-webpack-boilerplate package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     webpack-dev-server --devtool eval --progress --hot --content-base app
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs react-babel-webpack-boilerplate
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls react-babel-webpack-boilerplate
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     F:\something\react\react-babel-4\npm-debug.log
·

**Comment by yangshipo** [comment]
问题已经找到了，端口被占用。

**Comment by summerinsect** [comment]
怎么解决的？改了端口也没用
