### ISSUE TITLE
图片加载问题

### ISSUE THREAD

**Issue by wangzhiwei1888** [ruanyf/react-babel-webpack-boilerplate#29]
我现在 加了 "file-loader": "^0.9.0", "url-loader": "^0.5.7",这两个依赖
webpack.production.config修改如下
{ test: /\.(png|jpg)$/,include: path.resolve(__dirname, 'app'), loader: 'url?limit=50000'}
后，图片加载 app.css 文件里面的图片文件名MD5了，显示ok, 
jsx 里面加的图片文件名没MD5，显示没有找到图片。

**Comment by ruanyf** [comment]
可以看看 file-loader 的文档。这里很难判断是什么问题。
