### ISSUE TITLE
bundle.js MD5问题。

### ISSUE THREAD

**Issue by wangzhiwei1888** [ruanyf/react-babel-webpack-boilerplate#30]
将webpack.production.config里面的
output
修改为
filename: './bundle.[hash:8].js'
后
由于index.html文件是直接copy的
{ from: './app/index.html', to: 'index.html' },
里面的路径不能变成 hash:8 后缀的。

**Comment by ruanyf** [comment]
webpack 可以拿到 hash 文件名的，具体要查一下文档。
