### ISSUE TITLE
source map

### ISSUE THREAD

**Issue by chenkang084** [ruanyf/react-babel-webpack-boilerplate#31]
i am not sure why i change to devtool to :devtool: '#inline-source-map' or devtool: 'inline-source-map',
the jsx file can not add breakdown or not debug . when i change to eval ,it can debug . since the eval can not get the exactly lines , could you help me resolve the issue .
Thanks
chenkang084@163.com

**Comment by ruanyf** [comment]
Sorry. Have no idea of it.
