### ISSUE TITLE
PR: Add support for `eslint-plugin-compat`

### ISSUE THREAD

**Issue by amilajack** [ruanyf/react-babel-webpack-boilerplate#33]
[This eslint plugin](http://github.com/amilajack/eslint-plugin-compat) lints against APIs that are only supported by target browsers 🎉 Would a PR for this be welcome?

**Here's a demo of it in action**

![demo of plugin usage](https://raw.githubusercontent.com/amilajack/eslint-plugin-compat/master/eslint-plugin-compat-demo.gif)

**Comment by ruanyf** [comment]
ESLint complains not finding the plugin. Do you have any idea?

```bash
$ npm run lint 

> react-babel-webpack-boilerplate@1.2.5 lint /home/ruanyf/project/react-babel-webpack-boilerplate
> eslint 'app/**/*.@(js|jsx)'

Oops! Something went wrong! :(

ESLint couldn't find the plugin "eslint-plugin-compat".
```

**Comment by amilajack** [comment]
@ruanyf That was an error with the plugin it self due to an incorrect path to `recommended.json`. Just made a fix for that and made a PR for a full working version: https://github.com/ruanyf/react-babel-webpack-boilerplate/pulls

**Comment by ruanyf** [comment]
Found the reason. A `recommended.json` should be added under `lib/config` directory. 

The file is like following.

```javascript
{
  "parser": "babel-eslint",
  "rules": {
    "compat/compat": 2
  }
}
```

When the issue is resolved, I will merge the PR.

**Comment by amilajack** [comment]
Version `0.1.3` has `config` dir inside `lib` so everything works as expected. Added `npm run lint` to npm test.
