### ISSUE TITLE
A question about Server-Side Rendering.

### ISSUE THREAD

**Issue by micooz** [ruanyf/react-babel-webpack-boilerplate#4]
I noticed that you webpack jsx to client side. So React renders its components in the browser. Maybe it is not a good idea in some cases(performance, high dependency on JavaScript and poor SEO).

If I put React back to server, jsx hot-reloading on server-side seems a kind of problem.

I found that [react-hot-loader](https://github.com/gaearon/react-hot-loader) was deprecated, but [react-transform](https://github.com/gaearon/babel-plugin-react-transform) does not support Babel6 yet. Should I continue to use Babel5?

Any ideas? Thx :)

**Comment by ruanyf** [comment]
This boilerplate is just for the developing stage, not for production. In that case, you don't need hot-module-replacement.

Please visit https://github.com/ruanyf/react-demos/tree/master/demo13 for how to do react server rendering.

P.S. you should update to Babel 6.
