### ISSUE TITLE
webpack2 报了好多错

### ISSUE THREAD

**Issue by niki571** [ruanyf/react-babel-webpack-boilerplate#41]
package.json里面webpack写了latest，现在npm start就报了一堆错。
webpack2要求entry是个string/object，我自己改完这个又报了一个别的错，改完第二个报了第三个错。。。

webpack.config.js要大改了。。。

**Comment by xiguaaxigua** [comment]
表示遇到了同样的问题...

**Comment by niki571** [comment]
@xiguaaxigua 我改成了1.x将就着用😅

**Comment by xiguaaxigua** [comment]
@niki571 
`npm uninstall --save-dev webpack webpack-dev-server`
`npm install --save-dev webpack@2.1.0-beta.22 webpack-dev-server@1.9.0 `
我是这样搞的

**Comment by ruanyf** [comment]
不好意思，Webpack 的默认版本升级到了 2，我没来得及改，导致报错。

现在，已经改好了。`master`分支支持 Webpack 1，`webpack2`分支支持 Webpack 2。

上面报错的朋友，请更新一下代码，切换到`webpack2`分支，然后删掉并重装依赖，应该就没有问题了。

```bash
$ git pull
$ git checkout webpack2
$ rm -rf node_modules
$ npm install
```

**Comment by xiguaaxigua** [comment]
@ruanyf thks
