### ISSUE TITLE
你好我想使用你的脚手架加上nw.js 我该怎么改 我运行nw .无法打开

### ISSUE THREAD

**Issue by zzhgithub** [ruanyf/react-babel-webpack-boilerplate#45]
我想写一个 react 加上 node-webkit的应用 但是没有好的 脚手架，我想写多页面的应用不是单页的。请问我应该怎么组织代码？谢谢

**Comment by ruanyf** [comment]
这个脚手架不太合适 nw 项目。下面这个网址可能有帮助。https://github.com/nw-cn/awesome-nwjs
