### ISSUE TITLE
webpack.production.config.js is missing

### ISSUE THREAD

**Issue by soulmachine** [ruanyf/react-babel-webpack-boilerplate#6]
I don't see the file `webpack.production.config.js` in this repo, and `npm run deploy` will absolutely fail.

**Comment by ruanyf** [comment]
I intended to leave it to user for flexibility. You should create it by yourself. 

An easy way to do it is copy `webpack.config.js` to `webpack.production.config.js`.

**Comment by ruanyf** [comment]
fix it.

**Comment by soulmachine** [comment]
Thank you!
